FROM node:latest
RUN rm -rf app
RUN mkdir app
RUN git clone https://github.com/kelleryvo/StreamDream.git ./app
RUN cd ./app
RUN git fetch
RUN git checkout dev
RUN cd ..
WORKDIR /app
COPY env.list /app
COPY ./app/package.json /app
RUN npm install
COPY ./app /app
CMD node server.js
EXPOSE 8888
