FROM node:latest
RUN rm -rf app
RUN mkdir app
RUN ls
WORKDIR /StreamDream
RUN git clone https://github.com/kelleryvo/StreamDream.git
RUN ls
RUN git checkout dev --
RUN cd ..
RUN ls
WORKDIR /app
COPY env.list /app
COPY ./app/package.json /app
RUN npm install
COPY ./app /app
CMD node server.js
EXPOSE 8888
