TYPE=VIEW
query=select `stream_dream5`.`tbl_user`.`id` AS `id`,`stream_dream5`.`tbl_user`.`username` AS `username`,`stream_dream5`.`tbl_user`.`password` AS `password`,`stream_dream5`.`tbl_user`.`email` AS `email`,`stream_dream5`.`tbl_user`.`registration_date` AS `registration_date` from `stream_dream5`.`tbl_user`
md5=d5df74bb7776877d021a81e91ec70bc8
updatable=1
algorithm=0
definer_user=root
definer_host=localhost
suid=1
with_check_option=0
timestamp=2018-06-19 20:06:26
create-version=1
source=select `tbl_user`.`id` AS `id`,`tbl_user`.`username` AS `username`,`tbl_user`.`password` AS `password`,`tbl_user`.`email` AS `email`,`tbl_user`.`registration_date` AS `registration_date` from `tbl_user`
client_cs_name=utf8mb4
connection_cl_name=utf8mb4_general_ci
view_body_utf8=select `stream_dream5`.`tbl_user`.`id` AS `id`,`stream_dream5`.`tbl_user`.`username` AS `username`,`stream_dream5`.`tbl_user`.`password` AS `password`,`stream_dream5`.`tbl_user`.`email` AS `email`,`stream_dream5`.`tbl_user`.`registration_date` AS `registration_date` from `stream_dream5`.`tbl_user`
